name: ShatteredEmpiresExtensions
description: Additional features added to the server, made for the Shattered Empires SMP.
author: G_Rplayer
version: 3.1.0
api-version: 1.18
main: me.grplayer.ShatteredEmpires